import { escapeAttribute, escapeHtml } from "../html.mjs";
import { CAMPAIGN_DETAIL_TABS } from "../../campaign-detail-service.mjs";
import { renderCampaignRepliesOutcomes } from "./campaign-replies-outcomes.mjs";
import { renderCampaignAdvancedDelivery } from "./campaign-advanced-delivery.mjs";

export const CAMPAIGN_DETAIL_STYLESHEET_PATH = "assets/ui/campaign-detail.css";
const value = (input) => input === null || input === undefined || input === "" ? '<span class="campaign-detail-unavailable">Unavailable</span>' : escapeHtml(String(input));
const metric = (label, input) => `<div><dt>${escapeHtml(label)}</dt><dd>${value(input)}</dd></div>`;

function panel(view) {
  const overview = view.overview;
  if (view.selectedTab === "messages") {
    const steps = Array.isArray(view.messages.steps) ? view.messages.steps : [];
    // The drafted copy itself. A campaign whose steps exist must show them — a step count
    // alone reads as an empty tab, which is exactly the defect this panel had.
    const drafted = steps.map((step) => `<article class="campaign-detail-message"><h3>Step ${escapeHtml(String(step.stepNumber || 1))}${step.subject ? ` — ${escapeHtml(step.subject)}` : ""}</h3><pre class="campaign-detail-message-body">${escapeHtml(step.body || "")}</pre></article>`).join("");
    return `<section data-detail-panel="messages"><h2>Messages</h2>${drafted || `<dl>${metric("Format", view.messages.mode?.label)}${metric("Summary", view.messages.summary)}${metric("Sequence", view.messages.sequenceName)}${metric("Steps", view.messages.stepCount)}${metric("First subject", view.messages.firstSubject)}</dl>`}</section>`;
  }
  if (view.selectedTab === "audience") {
    const members = Array.isArray(view.audience.members) ? view.audience.members : [];
    const roster = members.map((member) => `<li><strong>${escapeHtml(member.name)}</strong>${member.organization ? ` — ${escapeHtml(member.organization)}` : ""} <span class="campaign-detail-audience-status" data-audience-status="${escapeAttribute(member.status)}">${escapeHtml(member.status)}${member.detail ? ` (${escapeHtml(member.detail)})` : ""}</span></li>`).join("");
    return `<section data-detail-panel="audience"><h2>Audience</h2><dl>${metric("Summary", view.audience.summary)}${metric("Included", view.audience.includedCount)}${metric("Excluded", view.audience.excluded?.count)}</dl>${roster ? `<ul class="campaign-detail-audience">${roster}</ul>` : ""}</section>`;
  }
  if (view.selectedTab === "replies") return `<section data-detail-panel="replies">${view.repliesOutcomes ? renderCampaignRepliesOutcomes(view.repliesOutcomes) : `<h2>Replies</h2><dl>${metric("Replies", view.replies.count)}</dl>`}</section>`;
  if (view.selectedTab === "results") return `<section data-detail-panel="results"><h2>Results</h2><dl>${metric("Summary", view.results.summary)}${Object.entries(view.results.metrics || {}).map(([key, input]) => metric(key.replaceAll(/([A-Z])/g, " $1"), input)).join("")}</dl></section>`;
  if (view.selectedTab === "activity") return `<section data-detail-panel="activity"><h2>Activity</h2><ol>${view.activity.map((item) => `<li><strong>${escapeHtml(item.kind)}</strong> ${value(item.status)} <time datetime="${escapeAttribute(item.occurredAt || "")}">${value(item.occurredAt)}</time></li>`).join("") || "<li>Activity unavailable</li>"}</ol></section>`;
  return `<section data-detail-panel="overview"><h2>Overview</h2><dl>${metric("Current status", overview.status?.label)}${metric("Next action", overview.nextAction)}${metric("Progress", overview.progress?.sent === null ? null : `${overview.progress.sent} sent`)}${metric("Schedule", overview.schedule?.scheduledAt)}${metric("Audience", overview.audience?.summary || overview.audience?.includedCount)}${metric("Outcome", overview.outcome?.outcomeSummary)}</dl></section>`;
}

export function renderCampaignDetail(view = {}) {
  if (!view.available) return `<section class="campaign-detail-state"><h1>Campaign not available</h1><p>This Campaign may have been removed or this account may not be allowed to view it.</p></section>`;
  const campaign = view.campaign;
  return `<section class="campaign-detail" data-campaign-detail data-campaign-identity="${escapeAttribute(campaign.stableIdentity)}"><header><p class="campaign-detail-eyebrow">Outreach campaign</p><h1>${escapeHtml(campaign.name || "Unnamed Campaign")}</h1><span class="campaign-detail-status">${escapeHtml(campaign.status.label)}</span></header><nav role="tablist" aria-label="Campaign detail">${CAMPAIGN_DETAIL_TABS.map((tab) => `<a role="tab" href="${escapeAttribute(campaign.href)}?tab=${tab.key}" aria-selected="${tab.key === view.selectedTab}">${escapeHtml(tab.label)}</a>`).join("")}</nav><div class="campaign-detail-content">${panel(view)}</div>${view.advancedDelivery ? renderCampaignAdvancedDelivery(view.advancedDelivery) : ""}<div class="campaign-detail-actions">${view.capabilities.pause ? '<button type="button" data-campaign-action="pause">Pause campaign</button>' : ""}${view.capabilities.resume ? '<button type="button" data-campaign-action="resume">Resume campaign</button>' : ""}${view.capabilities.press_run ? '<button type="button" data-campaign-action="press_run">Approve and run this campaign</button>' : ""}${view.capabilities.press_stop ? '<button type="button" data-campaign-action="press_stop">Stop campaign</button>' : ""}</div><p>Scheduled is not sent. Approved is not executed. Paused is not completed.</p></section>`;
}

// Browser runtime. Everything inside the template literal is shipped on every page load,
// so the reasoning lives out here rather than in the payload.
//
// observerQueued / loading / failedRouteKey are the recovery observer's re-entrancy state.
// Without them, load()'s own DOM writes retrigger the observer, which re-enters load(),
// which aborts the in-flight fetch and writes again — an unbounded microtask loop that
// freezes the tab on the loading state. Same latch shape social-home.mjs and
// automation-control-center.mjs use, plus two guards the original also needed: never
// re-enter while a load is in flight, and never auto-retry a route whose last load ended
// in an error (otherwise a failed load spins on every DOM mutation instead of freezing).
// A successful render clears the failure latch, so a genuine DOM wipe is still recovered.
export function campaignDetailBrowserSource() {
  return `(() => {
    "use strict";
    let controller=null;let sequence=0;
    let observerQueued=false;let loading=false;let failedRouteKey="";
    const resolution=()=>window.__LE_VNEXT_ROUTE_COMPATIBILITY?.resolve(location.hash||"");
    const routeKey=(current)=>current?current.identity+"?"+current.tab:"";
    function route(){const value=resolution();const query=new URLSearchParams(String(location.hash||"").split("?")[1]||"");return value?.kind==="object"&&value.objectType==="Campaign"&&!query.has("step")?{identity:value.sourceId,tab:query.get("tab")||"overview"}:null;}
    const target=()=>document.querySelector("main#app #item.page-section.active");
    const text=(tag,value,className="")=>{const node=document.createElement(tag);node.textContent=value===null||value===undefined||value===""?"Unavailable":String(value);if(className)node.className=className;return node;};
    function csrf(){return document.cookie.split(";").map((value)=>value.trim()).find((value)=>value.startsWith("leos_csrf="))?.slice("leos_csrf=".length)||"";}
    function valueList(panel,items){const dl=document.createElement("dl");for(const [label,value] of items){const box=document.createElement("div");box.append(text("dt",label),text("dd",value));dl.append(box);}panel.append(dl);}
    function render(payload,current){const host=target();if(!host)return;host.replaceChildren();const root=document.createElement("section");root.className="campaign-detail";root.dataset.campaignDetail="";root.dataset.campaignIdentity=payload.campaign.stableIdentity;const header=document.createElement("header");header.append(text("p","Outreach campaign","campaign-detail-eyebrow"),text("h1",payload.campaign.name||"Unnamed Campaign"),text("span",payload.campaign.status?.label,"campaign-detail-status"));root.append(header);const nav=document.createElement("nav");nav.setAttribute("role","tablist");nav.setAttribute("aria-label","Campaign detail");for(const item of ${JSON.stringify(CAMPAIGN_DETAIL_TABS)}){const link=document.createElement("a");link.role="tab";link.href=payload.campaign.href+"?tab="+item.key;link.textContent=item.label;link.setAttribute("aria-selected",String(item.key===current.tab));nav.append(link);}root.append(nav);const panel=document.createElement("section");panel.dataset.detailPanel=current.tab;panel.append(text("h2",current.tab[0].toUpperCase()+current.tab.slice(1)));if(current.tab==="messages"&&Array.isArray(payload.messages?.steps)&&payload.messages.steps.length){for(const step of payload.messages.steps){const article=document.createElement("article");article.className="campaign-detail-message";article.append(text("h3","Step "+(step.stepNumber||1)+(step.subject?" — "+step.subject:"")));const body=document.createElement("pre");body.className="campaign-detail-message-body";body.textContent=step.body||"";article.append(body);panel.append(article);}}
else if(current.tab==="messages")valueList(panel,[["Format",payload.messages?.mode?.label],["Steps",payload.messages?.stepCount],["First subject",payload.messages?.firstSubject]]);
else if(current.tab==="audience"){valueList(panel,[["Summary",payload.audience?.summary],["Included",payload.audience?.includedCount],["Excluded",payload.audience?.excluded?.count]]);const members=Array.isArray(payload.audience?.members)?payload.audience.members:[];if(members.length){const roster=document.createElement("ul");roster.className="campaign-detail-audience";for(const member of members){const row=document.createElement("li");const name=document.createElement("strong");name.textContent=member.name||"Unnamed contact";row.append(name);if(member.organization)row.append(document.createTextNode(" — "+member.organization));const status=document.createElement("span");status.className="campaign-detail-audience-status";status.dataset.audienceStatus=member.status||"";status.textContent=" "+(member.status||"")+(member.detail?" ("+member.detail+")":"");row.append(status);roster.append(row);}panel.append(roster);}}
else if(current.tab==="replies")valueList(panel,[["Replies",payload.repliesOutcomes?.summary?.totalReplies??payload.replies?.count],["Needs review",payload.repliesOutcomes?.summary?.needsReview]]);else if(current.tab==="results")valueList(panel,[["Summary",payload.results?.summary],["Sent",payload.results?.metrics?.sent],["Replies",payload.results?.metrics?.replies]]);else if(current.tab==="activity")valueList(panel,[["Activity items",payload.activity?.length]]);else valueList(panel,[["Current status",payload.overview?.status?.label],["Next action",payload.overview?.nextAction],["Audience",payload.overview?.audience?.summary],["Schedule",payload.overview?.schedule?.scheduledAt]]);root.append(panel);const actions=document.createElement("div");actions.className="campaign-detail-actions";const actionLabels={pause:"Pause campaign",resume:"Resume campaign",press_run:"Approve and run this campaign",press_stop:"Stop campaign"};for(const action of ["pause","resume","press_run","press_stop"]){if(payload.capabilities?.[action]!==true)continue;const button=document.createElement("button");button.type="button";button.dataset.campaignAction=action;button.textContent=actionLabels[action];button.addEventListener("click",()=>{if(action==="press_run"&&!window.confirm("Approve and run this press campaign?\\n\\nThis is the one approval: the assigned journalists are enrolled now and their pitch sends in the next weekday 8:00\\u201317:00 ET window, one touch each, no automated follow-up. A reply stops that journalist. One press campaign runs at a time.\\n\\nStop is available immediately after."))return;if(action==="press_stop"&&!window.confirm("Stop this press campaign now? Unsent pitches are archived immediately."))return;statusAction(action,payload.campaign.stableIdentity,button);});actions.append(button);}root.append(actions,text("p","Scheduled is not sent. Approved is not executed. Paused is not completed."));host.append(root);}
    async function statusAction(action,identity,button){button.disabled=true;const requestId="campaign-"+action+"-"+crypto.randomUUID().replaceAll("-","");const response=await fetch("/api/ui/outreach/campaign/"+encodeURIComponent(identity)+"/status-action",{method:"POST",credentials:"same-origin",headers:{"content-type":"application/json","x-csrf-token":csrf()},body:JSON.stringify({action,idempotencyKey:requestId})});if(response.ok)await load();else button.disabled=false;}
    async function load(){const current=route();const host=target();if(!current||!host)return;if(controller)controller.abort();controller=new AbortController();const requestId=++sequence;loading=true;const key=routeKey(current);host.replaceChildren(text("p","Loading Campaign…","campaign-detail-state"));try{const response=await fetch("/api/ui/outreach/campaign/"+encodeURIComponent(current.identity)+"?tab="+encodeURIComponent(current.tab),{credentials:"same-origin",headers:{accept:"application/json"},signal:controller.signal});if(response.status===401){failedRouteKey=key;host.replaceChildren(text("p","Session expired. Sign in again."));return;}if(response.status===403){failedRouteKey=key;host.replaceChildren(text("p","Campaign access required."));return;}if(!response.ok)throw new Error("request_failed");const payload=await response.json();if(requestId===sequence){failedRouteKey="";render(payload,current);}}catch(error){if(error.name!=="AbortError"&&requestId===sequence){failedRouteKey=key;host.replaceChildren(text("p","Campaign could not load. No records were changed."));}}finally{if(requestId===sequence)loading=false;}}
    window.addEventListener("hashchange",()=>setTimeout(()=>{failedRouteKey="";load();},0));
    new MutationObserver(()=>{if(observerQueued)return;observerQueued=true;requestAnimationFrame(()=>{observerQueued=false;const current=route();if(!current||loading)return;if(document.querySelector("[data-campaign-detail]"))return;if(failedRouteKey===routeKey(current))return;load();});}).observe(document.documentElement,{childList:true,subtree:true});
    setTimeout(load,0);
  })();`;
}
