import { escapeAttribute, escapeHtml } from "../html.mjs";
import { CAMPAIGN_DETAIL_TABS } from "../../campaign-detail-service.mjs";
import { renderCampaignRepliesOutcomes } from "./campaign-replies-outcomes.mjs";
import { renderCampaignAdvancedDelivery } from "./campaign-advanced-delivery.mjs";

export const CAMPAIGN_DETAIL_STYLESHEET_PATH = "assets/ui/campaign-detail.css";
const value = (input) => input === null || input === undefined || input === "" ? '<span class="campaign-detail-unavailable">Unavailable</span>' : escapeHtml(String(input));
const metric = (label, input) => `<div><dt>${escapeHtml(label)}</dt><dd>${value(input)}</dd></div>`;

function panel(view) {
  const overview = view.overview;
  if (view.selectedTab === "messages") return `<section data-detail-panel="messages"><h2>Messages</h2><dl>${metric("Format", view.messages.mode?.label)}${metric("Summary", view.messages.summary)}${metric("Sequence", view.messages.sequenceName)}${metric("Steps", view.messages.stepCount)}${metric("First subject", view.messages.firstSubject)}</dl></section>`;
  if (view.selectedTab === "audience") return `<section data-detail-panel="audience"><h2>Audience</h2><dl>${metric("Summary", view.audience.summary)}${metric("Included", view.audience.includedCount)}${metric("Excluded", view.audience.excluded?.count)}</dl></section>`;
  if (view.selectedTab === "replies") return `<section data-detail-panel="replies">${view.repliesOutcomes ? renderCampaignRepliesOutcomes(view.repliesOutcomes) : `<h2>Replies</h2><dl>${metric("Replies", view.replies.count)}</dl>`}</section>`;
  if (view.selectedTab === "results") return `<section data-detail-panel="results"><h2>Results</h2><dl>${metric("Summary", view.results.summary)}${Object.entries(view.results.metrics || {}).map(([key, input]) => metric(key.replaceAll(/([A-Z])/g, " $1"), input)).join("")}</dl></section>`;
  if (view.selectedTab === "activity") return `<section data-detail-panel="activity"><h2>Activity</h2><ol>${view.activity.map((item) => `<li><strong>${escapeHtml(item.kind)}</strong> ${value(item.status)} <time datetime="${escapeAttribute(item.occurredAt || "")}">${value(item.occurredAt)}</time></li>`).join("") || "<li>Activity unavailable</li>"}</ol></section>`;
  return `<section data-detail-panel="overview"><h2>Overview</h2><dl>${metric("Current status", overview.status?.label)}${metric("Next action", overview.nextAction)}${metric("Progress", overview.progress?.sent === null ? null : `${overview.progress.sent} sent`)}${metric("Schedule", overview.schedule?.scheduledAt)}${metric("Audience", overview.audience?.summary || overview.audience?.includedCount)}${metric("Outcome", overview.outcome?.outcomeSummary)}</dl></section>`;
}

export function renderCampaignDetail(view = {}) {
  if (!view.available) return `<section class="campaign-detail-state"><h1>Campaign not available</h1><p>This Campaign may have been removed or this account may not be allowed to view it.</p></section>`;
  const campaign = view.campaign;
  return `<section class="campaign-detail" data-campaign-detail data-campaign-identity="${escapeAttribute(campaign.stableIdentity)}"><header><p class="campaign-detail-eyebrow">Outreach campaign</p><h1>${escapeHtml(campaign.name || "Unnamed Campaign")}</h1><span class="campaign-detail-status">${escapeHtml(campaign.status.label)}</span></header><nav role="tablist" aria-label="Campaign detail">${CAMPAIGN_DETAIL_TABS.map((tab) => `<a role="tab" href="${escapeAttribute(campaign.href)}?tab=${tab.key}" aria-selected="${tab.key === view.selectedTab}">${escapeHtml(tab.label)}</a>`).join("")}</nav><div class="campaign-detail-content">${panel(view)}</div>${view.advancedDelivery ? renderCampaignAdvancedDelivery(view.advancedDelivery) : ""}<div class="campaign-detail-actions">${view.capabilities.pause ? '<button type="button" data-campaign-action="pause">Pause campaign</button>' : ""}${view.capabilities.resume ? '<button type="button" data-campaign-action="resume">Resume campaign</button>' : ""}</div><p>Scheduled is not sent. Approved is not executed. Paused is not completed.</p></section>`;
}

export function campaignDetailBrowserSource() {
  return `(() => {
    "use strict";
    let controller=null;let sequence=0;
    const resolution=()=>window.__LE_VNEXT_ROUTE_COMPATIBILITY?.resolve(location.hash||"");
    function route(){const value=resolution();const query=new URLSearchParams(String(location.hash||"").split("?")[1]||"");return value?.kind==="object"&&value.objectType==="Campaign"&&!query.has("step")?{identity:value.sourceId,tab:query.get("tab")||"overview"}:null;}
    const target=()=>document.querySelector("main#app #item.page-section.active");
    const text=(tag,value,className="")=>{const node=document.createElement(tag);node.textContent=value===null||value===undefined||value===""?"Unavailable":String(value);if(className)node.className=className;return node;};
    function csrf(){return document.cookie.split(";").map((value)=>value.trim()).find((value)=>value.startsWith("leos_csrf="))?.slice("leos_csrf=".length)||"";}
    function valueList(panel,items){const dl=document.createElement("dl");for(const [label,value] of items){const box=document.createElement("div");box.append(text("dt",label),text("dd",value));dl.append(box);}panel.append(dl);}
    function render(payload,current){const host=target();if(!host)return;host.replaceChildren();const root=document.createElement("section");root.className="campaign-detail";root.dataset.campaignDetail="";root.dataset.campaignIdentity=payload.campaign.stableIdentity;const header=document.createElement("header");header.append(text("p","Outreach campaign","campaign-detail-eyebrow"),text("h1",payload.campaign.name||"Unnamed Campaign"),text("span",payload.campaign.status?.label,"campaign-detail-status"));root.append(header);const nav=document.createElement("nav");nav.setAttribute("role","tablist");nav.setAttribute("aria-label","Campaign detail");for(const item of ${JSON.stringify(CAMPAIGN_DETAIL_TABS)}){const link=document.createElement("a");link.role="tab";link.href=payload.campaign.href+"?tab="+item.key;link.textContent=item.label;link.setAttribute("aria-selected",String(item.key===current.tab));nav.append(link);}root.append(nav);const panel=document.createElement("section");panel.dataset.detailPanel=current.tab;panel.append(text("h2",current.tab[0].toUpperCase()+current.tab.slice(1)));if(current.tab==="replies")valueList(panel,[["Replies",payload.repliesOutcomes?.summary?.totalReplies??payload.replies?.count],["Needs review",payload.repliesOutcomes?.summary?.needsReview]]);else if(current.tab==="results")valueList(panel,[["Summary",payload.results?.summary],["Sent",payload.results?.metrics?.sent],["Replies",payload.results?.metrics?.replies]]);else if(current.tab==="activity")valueList(panel,[["Activity items",payload.activity?.length]]);else valueList(panel,[["Current status",payload.overview?.status?.label],["Next action",payload.overview?.nextAction],["Audience",payload.overview?.audience?.summary],["Schedule",payload.overview?.schedule?.scheduledAt]]);root.append(panel);const actions=document.createElement("div");actions.className="campaign-detail-actions";for(const action of ["pause","resume"]){if(payload.capabilities?.[action]!==true)continue;const button=document.createElement("button");button.type="button";button.dataset.campaignAction=action;button.textContent=action==="pause"?"Pause campaign":"Resume campaign";button.addEventListener("click",()=>statusAction(action,payload.campaign.stableIdentity,button));actions.append(button);}root.append(actions,text("p","Scheduled is not sent. Approved is not executed. Paused is not completed."));host.append(root);}
    async function statusAction(action,identity,button){button.disabled=true;const requestId="campaign-"+action+"-"+crypto.randomUUID().replaceAll("-","");const response=await fetch("/api/ui/outreach/campaign/"+encodeURIComponent(identity)+"/status-action",{method:"POST",credentials:"same-origin",headers:{"content-type":"application/json","x-csrf-token":csrf()},body:JSON.stringify({action,idempotencyKey:requestId})});if(response.ok)await load();else button.disabled=false;}
    async function load(){const current=route();const host=target();if(!current||!host)return;if(controller)controller.abort();controller=new AbortController();const requestId=++sequence;host.replaceChildren(text("p","Loading Campaign…","campaign-detail-state"));try{const response=await fetch("/api/ui/outreach/campaign/"+encodeURIComponent(current.identity)+"?tab="+encodeURIComponent(current.tab),{credentials:"same-origin",headers:{accept:"application/json"},signal:controller.signal});if(response.status===401){host.replaceChildren(text("p","Session expired. Sign in again."));return;}if(response.status===403){host.replaceChildren(text("p","Campaign access required."));return;}if(!response.ok)throw new Error("request_failed");const payload=await response.json();if(requestId===sequence)render(payload,current);}catch(error){if(error.name!=="AbortError"&&requestId===sequence)host.replaceChildren(text("p","Campaign could not load. No records were changed."));}}
    window.addEventListener("hashchange",()=>setTimeout(load,0));new MutationObserver(()=>{if(route()&&!document.querySelector("[data-campaign-detail]"))load();}).observe(document.documentElement,{childList:true,subtree:true});setTimeout(load,0);
  })();`;
}
